# This is a basic workflow to help you get started with Actions

name: Periodic at 0500 utc

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: 0 08 * * *  # Every day at noon – https://crontab.guru

jobs:
  generate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate graphs
      run: |
        python estimate.py    
    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: HH
        author_email: haholien@gmail.com
        message: "Updated charts"
        add: "results/*"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
